[package]
name = "get_environment_variables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
widestring = "1.1.0"
winapi = { version = "0.3.9", features = ["winnt", "processenv", "minwindef"] }
